version: '3.7'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SECRET_KEY=Your_key
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=Your_key
      - STRIPE_TEST_SECRET_KEY=Your_key
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: